### ISSUE TITLE
Error when using `%%time` Jupyter magic

### ISSUE THREAD

**Issue by jrbourbeau** [eriknw/afar#10]
I found that when I run the following snippet in a JupyterLab cell

```python
%%time

import afar

with afar.run, remotely:
    import dask.array as da
    x = da.arange(10)
    result = x.sum().compute()    
```

I get the following error when `afar` attempts to inspect the current frame:

```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<timed exec> in <module>

~/mambaforge/envs/coiled-jrbourbeau-parquet-demo/lib/python3.9/site-packages/afar/core.py in __enter__(self)
    125                 raise RuntimeError("uh oh!")
    126             self.data = {}
--> 127         lines, offset = inspect.findsource(self._frame)
    128 
    129         while not lines[with_lineno].lstrip().startswith("with"):

~/mambaforge/envs/coiled-jrbourbeau-parquet-demo/lib/python3.9/inspect.py in findsource(object)
    833         lines = linecache.getlines(file)
    834     if not lines:
--> 835         raise OSError('could not get source code')
    836 
    837     if ismodule(object):

OSError: could not get source code
```

When I remove the `%%time` magic, no error is raised

**Comment by eriknw** [comment]
Thanks for giving `afar` a try! ❤️ 

This is a great example of source code not always being available.  Roughly speaking, the `%%time` magic and other IPython magics compile code into an AST, then exec the AST.  The frame generated from this doesn't know about source lines.

I agree that `%%time` is a natural thing to do when using `afar`, so this would be nice to support.  Some options:

- change afar to not use source lines.  Using source lines was chosen for simplicity.  I also experimented with using bytecode directly.  This is doable, but more complicated and might lead to subtle bugs.  It could also be a maintenance burden for supporting new versions of CPython and even other Python interpreters.  Although possible, I would prefer to avoid this for now, or leverage another library that handles the potential headaches here.  Tracing or other hacks may be possible as well.
- detect that the frame was generated by an IPython magic, and use `IPython` library to get the current code cell.

After poking around IPython for a bit, one way to do the latter could be:
```python
ip = IPython.get_ipython()
last_cell = next(ip.history_manager.get_range(start=-1))[-1]
```
I'd be fine with adding an IPython-specific hack to make this work.

**Comment by jrbourbeau** [comment]
Thanks for making it 🚀 

All the concerns you brought up regarding bytecode are totally valid. Since the `IPython` solution seems rather minimal, maybe we go with that initially and if other scenarios come up later down the line, reconsider more generic approaches (e.g. bytecode)
