### ISSUE TITLE
Send `print` statements back to the client

### ISSUE THREAD

**Issue by gjoseph92** [eriknw/afar#13]
I'm using `afar` to move graph-generation of a large collection onto the cluster, so my slow internet doesn't slow things down so much. I've found myself wanting to print a few statistics about the collection before I compute it.

I could make all this work by reusing futures and maybe returning some strings, but in the spirit of afar's magic, it would be very intuitive if `print` just... printed.

Perhaps https://github.com/dask/distributed/pull/5217 would make this possible?

EDIT: also must add, `afar` is amazing! What a joy to use.

**Comment by eriknw** [comment]
Hi @gjoseph92!

This is a perfect use case for `afar`; thanks for giving it a try ❤️  

I agree: it would be great if `print` printed.  The PR you shared looks helpful/promising.

Alternatively, we could overwrite `builtins.print` in `afar` when executing remotely, log the messages, and send this back to the client ourselves.  Should be straightforward.  I'm about to go on vacation for a week, so I may wait to see what happens with the Dask PR.

**Comment by eriknw** [comment]
This is partly completed.  I capture printing and #18 and send it back to the client in one go.  I was planning on extending this with something like distributed Queues to send output back in realtime, but, alas, [Data Streams and Queues](https://distributed.dask.org/en/latest/queues.html) is no longer supported.  I'm still hopeful we can figure out a way to send output back in realtime.

Anyway, `afar` 0.4.0 has been released with print support.  Hopefully I didn't break anything, 'cause I am now on vacation!

**Comment by jrbourbeau** [comment]
Enjoy your time off @eriknw! 

I suspect we can make use to https://github.com/dask/distributed/pull/5217 to send back realtime results to the client
