### ISSUE TITLE
KeyboardInterrupt-ing `afar.get` doesn't cancel the future

### ISSUE THREAD

**Issue by gjoseph92** [eriknw/afar#15]
It would be nice if ctrl-c during an `afar.get` block cancelled whatever was running on the cluster.

**Comment by jrbourbeau** [comment]
On a related note, I found that running `future.cancel()` on a Future returned by `afar` doesn't end up canceling the tasks that were submitted using the same `afar` call

**Comment by eriknw** [comment]
Good suggestions.  I'm on it!

**Comment by eriknw** [comment]
> On a related note, I found that running future.cancel() on a Future returned by afar doesn't end up canceling the tasks that were submitted using the same afar call

Most of the work is done by the parent task, which creates a dictionary of results (including repr info if necessary).  The user-facing Future object is a simple task that gets an item from the dict.  So, if you cancel a Future from `afar`, would you want to also cancel all its siblings and the parent?

Note that in #17, you can now do `run.cancel()` to cancel pending tasks.
