### ISSUE TITLE
IPython magic?

### ISSUE THREAD

**Issue by jrbourbeau** [eriknw/afar#16]
Python `afar`s API today looks like:

```python
with afar.run, remotely:
    import dask_cudf
    df = dask_cudf.read_parquet("s3://...")
    result = df.sum().compute()
```

This is great, but the syntax seems a bit magical. Particularly in IPython or Jupyter, using a `%%afar` magic might be a more natural fit for users:

```python
%%afar

import dask_cudf
df = dask_cudf.read_parquet("s3://...")
result = df.sum().compute()
```

Perhaps @Carreau could provide some guidance on how we could turn `with afar.run, remotely:` into a magic command? I've got a feeling he's done this a time or two before ; )

**Comment by eriknw** [comment]
👍  This would be great!

I can move some things around to make this easier.

**Comment by eriknw** [comment]
And I suspect it would have been much easier to begin with an IPython magic instead of the context manager.

**Comment by Carreau** [comment]
The closest I can think of is [the `%%time` magic](https://github.com/ipython/ipython/blob/75459394ea3f5ac7ab92807d3fcc930183fe58c0/IPython/core/magics/execution.py#L1195-L1338) you can look at timeit as well in the same file, but it's more complicated. 

Honestly as a first pass I would just indent indent with 4 space and insert the context manager and imports at the top.
See how far it goes.

As variable names, and import can clash, you can either use long uniques names, like `import afar as __cthulhu_the_remote_compute_monster_dont_use_me`, you can ast.parse and rewrite the module ast using variables that are in text form invalid python syntax (sometime it works). Like with ast you can introduce a variable whose name is `afar-module`, and `run-method`, and `remote-function` which nobody can actually type (and technically variables names in the ast don't need to be strings if you are really crazy, but that may break other stuff and may not work in recent Python versions but it used to).

I haven't tried afar so I don't have further thoughts right now, but let me know if that get you started, and I might try to help a bit later once my todo list is in a better shape.

**Comment by eriknw** [comment]
Thanks for chiming in @Carreau .  I took a stab at this in #22.  This is my first IPython magic 🤞 

The main question I have is how do I test magics and other code that relies on running in IPython/Jupyter?  Ideally, I would like to capture line coverage as part of CI as well.

**Comment by Carreau** [comment]
> The main question I have is how do I test magics and other code that relies on running in IPython/Jupyter? Ideally, I would like to capture line coverage as part of CI as well.

It's not might not be that straightforward, but as the magics are mainly a wrapper around your `_run` function I wouldn't worry to much about it. 

If you still need you can : 

```python
def test_foo():
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
    ip = TerminalInteractiveShell.instance() # warning, singleton.
    ip.run_cell(code)
    ip.run_line_magic(magic_name, line)
    ip.run_cell_magic(magic_name, line, cell)
```
