### ISSUE TITLE
Repr of final expression no longer displayed in Jupyter with afar 0.4.0

### ISSUE THREAD

**Issue by gjoseph92** [eriknw/afar#20]
I enjoyed this feature (as seen on read-me!)
```python
with afar.run, remotely:
    three + seven
# displays 10!
```

But with the newest afar version, I only see
```
✨ Running afar... ✨
```

Not much bother, since I can use
```python
with afar.get, remotely:
    result = three + seven
result
```
but it was handy while available.

**Comment by eriknw** [comment]
Oh no!  Thanks for the report.

I discovered a race condition with how I'm updating outputs using `ipywidgets`: https://github.com/jupyter-widgets/ipywidgets/issues/3260

I have a workaround.  I'll push a bugfix release shortly.

**Comment by eriknw** [comment]
This is actually one of my favorite experiences when using `afar`.  So nice, and I never want to give it up.

I just released `afar` version 0.4.1, which hopefully fixes this.  If it doesn't, please reopen!

@gjoseph92  I'm curious: were you using JupyterLab by chance?  Things should work better now in JupyterLab, but there's still an issue I need to figure out and report upstream.  Hopefully the only impact this will have on users of `afar` is an occasional 0.5 second delay to display the output.

**Comment by eriknw** [comment]
Oh, and new with `afar` version 0.4 is the result of the expression will be shown asynchronously.  Previously, we had to block to display the result.

**Comment by gjoseph92** [comment]
@eriknw I was using JupyterLab. I haven't tested 0.4.1 yet, but thanks for the fix and I'll let you know soon if I have any issues with it!
